# service to expose middleware within the cluster
apiVersion: v1
kind: Service
metadata:
  name: middleware-svc
spec:
  type: ClusterIP
  selector:
    app: middleware-app
  ports:
  - port: 80
    targetPort: 80