# service to expose backend db within the cluster
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: ClusterIP
  selector:
    app: backend-db
  ports:
  - port: 3306
    targetPort: 3306