apiVersion: batch/v1
kind: Job
metadata:
  name: jobsalpine
spec:
  template:
    metadata:
      labels:
        app: jobsalpine
    spec:
      containers:
        - name: jobsalpine
          image: alpine
          args:
            - /bin/sh
            - -c
            - -sleep 2m
      restartPolicy: OnFailure