apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  # add namespace using "kubectl create namespace dev"
  namespace: dev
spec:
  containers:
    - name: httpd
      image: httpd
      ports:
        - containerPort: 80