---
apiVersion: v1 # select the app version
kind: Pod # kind of resource want to create
metadata:
  name: sample-httpd # pod name
  labels:
    name: httpd # label
spec:
  containers:
  - name: httpd # name of the container
    image: httpd # the image which your want to deploy from Docker hub 
    resources: # you can limit the cpu resources
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports: # container port to access the service
      - containerPort: 80
        protocol: TCP
    volumeMounts: # volume mount to the container / pod
      - mountPath: /data
        name: data-volume
  volumes: # the volume mapped to host machine non persistent data
  - name: data-volume
    emptyDir: {}

# to check the created pod use below commends
# kubectl get pods